Unbreak build due to ambiguous call to floor (#3654)
Summary:
Build is breaking on Mac (seems fine on CI):

```
glow/tests/unittests/OperatorTest.cpp:6101:28: fatal error: call to 'floor' is ambiguous
  uint32_t bin = (uint32_t)floor(bin_calc);
                           ^~~~~
```
Pull Request resolved: https://github.com/pytorch/glow/pull/3654

Differential Revision: D18052475

Pulled By: jfix71

fbshipit-source-id: 6b662e72dd3bdc5e9d9c70da3320c6ee21484d77